### ISSUE TITLE
forge error upon opening minecraft

### ISSUE THREAD

**Issue by kerrschtein** [elucent/SimplyTea#14]
As the title says, I'm having an issue upon opening minecraft. 
Here's the error log: [latest.log](https://github.com/elucent/SimplyTea/files/3660695/latest.log)
And here's what it looks like when I start up the game: 
![Screenshot_35](https://user-images.githubusercontent.com/55864549/65738580-59fb0600-e0b0-11e9-97b4-8a466aa2aff1.png)

Any help is greatly appreciated, as I was really looking forward to using this mod! Sorry if this isn't how you do things on github, I'm really new to MC modding and github.

**Comment by KnightMiner** [comment]
Did some testing, looks like this is a bug on Biome's O Plenty's side. Instead of using the biome registration event to add biome types, they use FMLCommonSetupEvent, so as a result when I fetch the list of biomes there it gets modified while I am iterating it.

I'll see what I can do from my side, but since Forge removed postInit and alike there is not a lot of other places I can add the feature.

**Comment by kerrschtein** [comment]
Thank you very much, I've been able to play since the error only happens every so often, but it's still something I felt I should report!

**Comment by KnightMiner** [comment]
Fixed in 2.0.4
