### ISSUE TITLE
Conflict with NoMoWanderer?

### ISSUE THREAD

**Issue by Giintaras** [elucent/SimplyTea#26]
Hello everyone, possible conflict with NoMoWanderer mod? I have this crash, when both mods are present. Posted on NoMoWanderer aswell. Here's pastebin link: https://pastebin.com/GYwu46Gv

**Comment by KnightMiner** [comment]
Post your full game log. Forge has this dumb bug where crashes during client setup get blamed on the first mod that has a block colors handler, so the actual problem is hidden in the logs.

**Comment by Giintaras** [comment]
Sorry, my bad! Please let me know if there is anything else I can do! Link:  https://pastebin.com/SbdFM7EK

**Comment by KnightMiner** [comment]
That is the wrong log. I need the log from the same game where it crashed, I would expect to see the crash at the end of the log. Simply Tea is not even installed in that log.

**Comment by Giintaras** [comment]
Sorry, my bad.. Will try again now and see if I can get a log for you. The problem is that the loader just stops no crash report nothing, just exits :/ and Im not sure which one you need here, are these fine? 

[debug-1.log](https://github.com/KnightMiner/SimplyTea/files/4730210/debug-1.log)
[2020-06-04-1.log](https://github.com/KnightMiner/SimplyTea/files/4730211/2020-06-04-1.log)

Edit: Crash log too: 
[crash-2020-06-04_14.12.27-client.txt](https://github.com/KnightMiner/SimplyTea/files/4730218/crash-2020-06-04_14.12.27-client.txt)

**Comment by KnightMiner** [comment]
That most recent crash is from bonsaitrees2, but same case of its not caused by them. As I said the problem really has nothing to do with my mod (or bonsai trees), but for some reason your game logs are not providing any helpful details. Even more strangely, the logs do not make any reference to having crashed at all, which I have never seen happen.

Without useful information in the logs, I really cannot help you find the problem. I can just tell you the crash is not caused by Simply Tea or by Bonsai Trees, they are just getting stuck with the error. Not sure what else I can say to help you debug this except try removing mods until you find which one crashes.

Edit: if you by any chance have a `latest.log`, that is normally what I look for. You should at the bottom of the log see the same contents as that crash report file. If you cannot find one such log, my best guess is one of your many mods is somehow breaking crash reporting as well.
