### ISSUE TITLE
Error while loading

### ISSUE THREAD

**Issue by SamhitApple** [elucent/SimplyTea#34]
I get this error when loading the game; I play on 1.16.4

Log file here: https://pastebin.com/PCW6huhH

**Comment by KnightMiner** [comment]
What happens when you test with fewer mods? Specifically, test without Charm loaded, I see mention of that mod in the stacktrace.

**Comment by SamhitApple** [comment]
I tried removing Charm and loaded, all the items seem to be in-game but I couldn't find any natural tea plants generating in the world, I've searched quite a bit! Note that I have 3 Biome altering mods installed; Traverse, BetterEndForge, Voyage.

**Comment by KnightMiner** [comment]
That is a separate issue, if you want to look into that more open a new ticket, bit my assumption is you are just unlucky. The trees are a bit rare. They should appear in any type of forest biome.

Since Charm appeared to have caused your crash, open an issue on the Charm issue tracker and link it here

**Comment by SamhitApple** [comment]
Oh! The main Charm page is labled for Fabric now! The Forge version is "Charm Reforged". I installed the right one and it loaded. But IDK how to describe it, the rendering was kinda funky; it was grainy and noisy just for a few blocks around! Hope you understand it, IDK how to tell it!

**Comment by KnightMiner** [comment]
Screenshot? Pictures are surprisingly good for describing a visual issue.

**Comment by SamhitApple** [comment]
I removed VanillaTweaks, and it's fixed now! Cuz I think Charm combined with VanillaTweaks creates issues like that. But still I don't find tea plants spawning in anywhere; I've searched plains, forests and other relevant biomes!

**Comment by SamhitApple** [comment]
And the weird rendering thing is back again! This time I took a screenshot of it! Zoom in closely and look, it's not that noticeable in an image but while playing the game it just is super evident; all that noisy grainy stuff in the view!
![Screenshot (133)](https://user-images.githubusercontent.com/76992008/104086975-5cbc4300-5282-11eb-945d-0887f09026c9.png)

**Comment by KnightMiner** [comment]
You sure you are not talking about vanilla mipmapping? In any case, you have went far beyond the original issue.

I suggest you test without my mod to verify that this is actually related. If it happens with just my mod installed, open an new issue. Closing this one since the original issue was about a crash that no longer happens.
